### PR TITLE
Fix rm hard link problem and resolve cache leak

### PR DESCRIPTION
**Pull request by RoyWFHuang**

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
There's no need to include section headers like "Description" in your git commit messages. Always opt for clear and descriptive language that explains your reasoning and the methods you employed to fix a specific problem.

**Comment by RoyWFHuang** [comment]
> There's no need to include section headers like "Description" in your git commit messages. Always opt for clear and descriptive language that explains your reasoning and the methods you employed to fix a specific problem.

Complete, leaving only bug description and solution

**Comment by jserv** [comment]
> Complete, leaving only bug description and solution

Refine the git commit messages by validating their English grammar.

**Comment by RoyWFHuang** [comment]
> > Complete, leaving only bug description and solution
> 
> Refine the git commit messages by validating their English grammar.

Refine the commit messages, please review them, thanks.

**Review by jserv — CHANGES_REQUESTED** [review]
Read https://cbea.ms/git-commit/ carefully and enforce the rules.

**Comment by jserv** [comment]
Thank @RoyWFHuang for contributing!

**Pull request merged**
