### PR TITLE
Fix the padding of remaining space of inode store

### PR DESCRIPTION
**Pull request by colinyoyo26**
Fill the remaining space of block with unused inodes.

### CODE REVIEW

**Comment by jserv** [comment]
Improve git commit message to address your changes.

**Comment by colinyoyo26** [comment]
I've improved it!

**Comment by jserv** [comment]
The subject should be changed accordingly to reflect unused inodes.

**Comment by colinyoyo26** [comment]
Thanks for advice, I've modified the commit message to make it more clear.

**Pull request merged**
