### PR TITLE
Change parameter to initialize new inode in Linux 6.3

### PR DESCRIPTION
**Pull request by fewletter**
Change the parameter to initialize new inode in creating new file system, and thanks to [@cbkadal](https://github.com/cbkadal) for reporting [Issue#25](https://github.com/sysprog21/simplefs/issues).

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Rebase the latest master branch and resolve the conflicts.

**Comment by jserv** [comment]
If you would like to close a pull request, there must be an explicit reason.

**Comment by fewletter** [comment]
I'd like to create a new branch for [commit 235a87c](https://github.com/fewletter/simplefs/commit/235a87ca7bddfec51dd32ff186cc46020228bfd2) to pull request.

**Comment by jserv** [comment]
> I'd like to create a new branch for [commit 235a87c](https://github.com/fewletter/simplefs/commit/235a87ca7bddfec51dd32ff186cc46020228bfd2) to pull request.

Next time, you can simply run `git rebase -i` and then `git push --force` within the same pull request.

**Pull request closed without merging**
